// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmPv1g-n3vTG9r-RVmz2awiOb-ZVgW0RM',
    appId: '1:1018115771796:web:5ca4375cb724511b839381',
    messagingSenderId: '1018115771796',
    projectId: 'checkpointpos-6e50f',
    authDomain: 'checkpointpos-6e50f.firebaseapp.com',
    storageBucket: 'checkpointpos-6e50f.appspot.com',
    measurementId: 'G-5YCF745H2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyb2UTNKsAXM24zVI8gCo9e3wLF0ONyi4',
    appId: '1:1018115771796:android:c0818f97ff3da13d839381',
    messagingSenderId: '1018115771796',
    projectId: 'checkpointpos-6e50f',
    storageBucket: 'checkpointpos-6e50f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABDfOSz3dYNciyucdD8CS668JsQWnEEsI',
    appId: '1:1018115771796:ios:746fc641f1b26ed9839381',
    messagingSenderId: '1018115771796',
    projectId: 'checkpointpos-6e50f',
    storageBucket: 'checkpointpos-6e50f.appspot.com',
    iosBundleId: 'com.example.posAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABDfOSz3dYNciyucdD8CS668JsQWnEEsI',
    appId: '1:1018115771796:ios:746fc641f1b26ed9839381',
    messagingSenderId: '1018115771796',
    projectId: 'checkpointpos-6e50f',
    storageBucket: 'checkpointpos-6e50f.appspot.com',
    iosBundleId: 'com.example.posAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmPv1g-n3vTG9r-RVmz2awiOb-ZVgW0RM',
    appId: '1:1018115771796:web:8a5fbfdea4f02f4f839381',
    messagingSenderId: '1018115771796',
    projectId: 'checkpointpos-6e50f',
    authDomain: 'checkpointpos-6e50f.firebaseapp.com',
    storageBucket: 'checkpointpos-6e50f.appspot.com',
    measurementId: 'G-VVZ3Q26WM8',
  );
}
